aliases:
    payeverpayment-payever-payment-component$: payeverpayment/js/app/components/payever-payment-component
dynamic-imports:
    payeverpayment:
        - payeverpayment-payever-payment-component
